---
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
  Include:
    - '**/*.rb'
    - 'Gemfile'
    - 'Rakefile'
    - '*.gemspec'
  TargetRubyVersion: 2.2

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
